sudo: required
services:
  - docker

before_install:
  - docker build -t mgviero/vue-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mgviero/vue-test npm run lint

after_success:
  - docker build -t hotrats/complex-client ./client
  - docker build -t hotrats/complex-nginx ./nginx
  - docker build -t hotrats/complex-server ./server
  - docker build -t hotrats/complex-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push hotrats/complex-client
  - docker push hotrats/complex-nginx
  - docker push hotrats/complex-server
  - docker push hotrats/complex-worker
