version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
  redis:
    image: redis:latest
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      - PGDATABASE=postgresql+asyncpg://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgres_data:
